### ISSUE TITLE
Multiline when reconnect

### ISSUE THREAD

**Issue by ardhinugroho** [lucadentella/SerialMonitor#1]
Hay Lucadentella

I found bug when i am try to reconnect. 
Received Textbox show multiple line, this show received string as many buttons are clicked

Thank for your great work

**Comment by ardhinugroho** [comment]
Solved

The problem is chrome.serial.onReceive.addListener(onReceive); called every connect button is clicked

I move to starting state, after updateGUI(); line

**Comment by lucadentella** [comment]
Hi, thanks for your comment. If you solve, please open a pull request, I'll be happy to include your change in my code
